/u/zelalae2/miniconda/envs/zero/lib/python3.9/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/u/zelalae2/miniconda/envs/zero/lib/python3.9/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
`torch_dtype` is deprecated! Use `dtype` instead!
Traceback (most recent call last):
  File "/projects/illinois/eng/cs/jimeng/zelalae2/scratch/DeepRetrieval/code/src/eval/SearchEngine/eval_pubmed.py", line 203, in <module>
    main()
  File "/projects/illinois/eng/cs/jimeng/zelalae2/scratch/DeepRetrieval/code/src/eval/SearchEngine/eval_pubmed.py", line 199, in main
    tokenizer, model = load_model(args.model_path)
  File "/projects/illinois/eng/cs/jimeng/zelalae2/scratch/DeepRetrieval/code/src/eval/SearchEngine/eval_pubmed.py", line 33, in load_model
    model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation="flash_attention_2", torch_dtype=torch.bfloat16)
  File "/u/zelalae2/miniconda/envs/zero/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 604, in from_pretrained
    return model_class.from_pretrained(
  File "/u/zelalae2/miniconda/envs/zero/lib/python3.9/site-packages/transformers/modeling_utils.py", line 288, in _wrapper
    return func(*args, **kwargs)
  File "/u/zelalae2/miniconda/envs/zero/lib/python3.9/site-packages/transformers/modeling_utils.py", line 5106, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/u/zelalae2/miniconda/envs/zero/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 419, in __init__
    super().__init__(config)
  File "/u/zelalae2/miniconda/envs/zero/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2197, in __init__
    self.config._attn_implementation_internal = self._check_and_adjust_attn_implementation(
  File "/u/zelalae2/miniconda/envs/zero/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2807, in _check_and_adjust_attn_implementation
    applicable_attn_implementation = self.get_correct_attn_implementation(
  File "/u/zelalae2/miniconda/envs/zero/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2835, in get_correct_attn_implementation
    self._flash_attn_2_can_dispatch(is_init_check)
  File "/u/zelalae2/miniconda/envs/zero/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2557, in _flash_attn_2_can_dispatch
    raise ValueError(
ValueError: FlashAttention2 has been toggled on, but it cannot be used due to the following error: Flash Attention 2 is not available on CPU. Please make sure torch can access a CUDA device.
